gtk-osx: Pipfile requires name for source
Otherwise an error is thrown:

pipenv.vendor.plette.models.base.ValidationError: {'url': 'https://pypi.python.org/simple', 'verify_ssl': True}
name: required field